version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch

    working_directory: ~/build

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: ./mvnw dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: ./mvnw clean verify
