/*
 * This file is generated by jOOQ.
 */
package com.revolut.transfer.persistence.jooq;


import com.revolut.transfer.persistence.jooq.tables.Account;
import com.revolut.transfer.persistence.jooq.tables.Transaction;
import com.revolut.transfer.persistence.jooq.tables.Transfer;
import com.revolut.transfer.persistence.jooq.tables.records.AccountRecord;
import com.revolut.transfer.persistence.jooq.tables.records.TransactionRecord;
import com.revolut.transfer.persistence.jooq.tables.records.TransferRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<TransactionRecord> CONSTRAINT_F = UniqueKeys0.CONSTRAINT_F;
    public static final UniqueKey<TransferRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TransactionRecord, AccountRecord> FK_TRANSACTION_ACCOUNT_ID = ForeignKeys0.FK_TRANSACTION_ACCOUNT_ID;
    public static final ForeignKey<TransferRecord, AccountRecord> FK_TRANSFER_SOURCE_ACCOUNT_ID = ForeignKeys0.FK_TRANSFER_SOURCE_ACCOUNT_ID;
    public static final ForeignKey<TransferRecord, AccountRecord> FK_TRANSFER_TARGET_ACCOUNT_ID = ForeignKeys0.FK_TRANSFER_TARGET_ACCOUNT_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> CONSTRAINT_E = Internal.createUniqueKey(Account.ACCOUNT, "CONSTRAINT_E", Account.ACCOUNT.ID);
        public static final UniqueKey<TransactionRecord> CONSTRAINT_F = Internal.createUniqueKey(Transaction.TRANSACTION, "CONSTRAINT_F", Transaction.TRANSACTION.ID);
        public static final UniqueKey<TransferRecord> CONSTRAINT_7 = Internal.createUniqueKey(Transfer.TRANSFER, "CONSTRAINT_7", Transfer.TRANSFER.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<TransactionRecord, AccountRecord> FK_TRANSACTION_ACCOUNT_ID = Internal.createForeignKey(com.revolut.transfer.persistence.jooq.Keys.CONSTRAINT_E, Transaction.TRANSACTION, "FK_TRANSACTION_ACCOUNT_ID", Transaction.TRANSACTION.ACCOUNT_ID);
        public static final ForeignKey<TransferRecord, AccountRecord> FK_TRANSFER_SOURCE_ACCOUNT_ID = Internal.createForeignKey(com.revolut.transfer.persistence.jooq.Keys.CONSTRAINT_E, Transfer.TRANSFER, "FK_TRANSFER_SOURCE_ACCOUNT_ID", Transfer.TRANSFER.SOURCE_ACCOUNT_ID);
        public static final ForeignKey<TransferRecord, AccountRecord> FK_TRANSFER_TARGET_ACCOUNT_ID = Internal.createForeignKey(com.revolut.transfer.persistence.jooq.Keys.CONSTRAINT_E, Transfer.TRANSFER, "FK_TRANSFER_TARGET_ACCOUNT_ID", Transfer.TRANSFER.TARGET_ACCOUNT_ID);
    }
}
