/*
 * This file is generated by jOOQ.
 */
package com.revolut.transfer.persistence.jooq;


import com.revolut.transfer.persistence.jooq.tables.Account;
import com.revolut.transfer.persistence.jooq.tables.Transaction;
import com.revolut.transfer.persistence.jooq.tables.Transfer;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 618199176;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public final Account ACCOUNT = com.revolut.transfer.persistence.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.TRANSACTION</code>.
     */
    public final Transaction TRANSACTION = com.revolut.transfer.persistence.jooq.tables.Transaction.TRANSACTION;

    /**
     * The table <code>PUBLIC.TRANSFER</code>.
     */
    public final Transfer TRANSFER = com.revolut.transfer.persistence.jooq.tables.Transfer.TRANSFER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Transaction.TRANSACTION,
            Transfer.TRANSFER);
    }
}
